# Generated by Django 4.2.5 on 2023-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='enter title of the article', max_length=100)),
                ('summury', models.TextField(help_text='enter summury of the article', max_length=500)),
                ('image', models.ImageField(help_text='Enter article photo', upload_to='images/article_photos/')),
                ('content', models.TextField(help_text='enter content of the article')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
