# Generated by Django 4.2.5 on 2023-09-14 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Enter user name', max_length=20)),
                ('photo', models.ImageField(help_text='Enter profile photo', upload_to='images/profile_photos/')),
                ('first_name', models.CharField(help_text='Enter full name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('phone_number', models.CharField(default='+375 (29) xxx-xx-xx', max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
            ],
        ),
    ]
