# Generated by Django 4.2.5 on 2023-09-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_position_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='enter Promocode', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
