# Generated by Django 4.2.5 on 2023-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='enter employee position', max_length=50)),
                ('company_name', models.CharField(help_text='enter company name', max_length=50)),
                ('city', models.CharField(help_text='enter city', max_length=50)),
                ('job_character', models.CharField(help_text='enter job character', max_length=50)),
                ('schedule', models.CharField(help_text='enter schedule', max_length=50)),
                ('employment', models.CharField(help_text='enter employement', max_length=50)),
                ('experience', models.CharField(help_text='enter experience', max_length=50)),
                ('education', models.CharField(help_text='enter education', max_length=50)),
                ('description', models.TextField(help_text='enter vacancy description')),
                ('salary', models.CharField(help_text='enter salary', max_length=50)),
            ],
        ),
    ]
